### ISSUE TITLE
CI について

### ISSUE THREAD

**Issue by a01sa01to** [saitamau-maximum/ui#1]
@sor4chi scope の設定ちがくない？あと GitHub Packages を使いたい (+ パッケージ名は `@saitamau-maximum/ui` にしよう)

https://github.com/saitamau-maximum/ui/blob/a8e8f3e0c6e5a43343f9f0a51624945222a92308/.github/workflows/format.yml#L19-L21

https://github.com/saitamau-maximum/ui/blob/a8e8f3e0c6e5a43343f9f0a51624945222a92308/.github/workflows/lint.yml#L19-L21

**Comment by sor4chi** [comment]
忘れてた、直しときます

**Comment by sor4chi** [comment]
GitHub packageにこだわるのはなんか理由ある？

**Comment by a01sa01to** [comment]
ただ npm Organization を作らなくていいから楽かなーと思っただけ
Organization が増えると引継ぎがめちゃくちゃ大変になりそうなので

プロジェクトルートに `.npmrc` 置いて

```
@saitamau-maximum:registry=https://npm.pkg.github.com
```

すればいいらしいので利便性はあまり npmjsorg とはあまり変わらないのかなーといった印象があり

**Comment by sor4chi** [comment]
なるほど...？
