### ISSUE TITLE
CI の改善

### ISSUE THREAD

**Issue by a01sa01to** [saitamau-maximum/ui#4]
lint.yml も同様っぽい...？

- 2 回やってる https://github.com/saitamau-maximum/ui/blob/548c9f4b6ba18946abcb025e3ea4dfc5af8ab666/.github/workflows/format.yml#L10-L14
- Matrix が定義されてないので空文字列になる https://github.com/saitamau-maximum/ui/blob/548c9f4b6ba18946abcb025e3ea4dfc5af8ab666/.github/workflows/format.yml#L15
- cache 周りは setup-pnpm を setup-node より前に持ってきて、setup-node に `cache: pnpm` を渡すと一瞬 https://github.com/saitamau-maximum/ui/blob/548c9f4b6ba18946abcb025e3ea4dfc5af8ab666/.github/workflows/format.yml#L29-L47 ここら辺いらなくなりそう (ref: https://github.com/saitamau-maximum/blog/blob/f290d0e561aef6d2c8b266a9fbe2b165518bc2e7/.github/workflows/deploy.yml#L26-L34)

**Comment by sor4chi** [comment]
そのキャッシュ方法だとダメだったみたいな話じゃなかったっけ？w

**Comment by sor4chi** [comment]
ちゃんと動いてるからmatrix消し忘れてた

**Comment by a01sa01to** [comment]
> そのキャッシュ方法だとダメだったみたいな話じゃなかったっけ？w

#6 の checks を見てもらうと動いてるんですよねぇ
(何なら saitamau-maximum/blog でも動いてる)

> ちゃんと動いてるからmatrix消し忘れてた

もし今後複数バージョンで動かす場合を考えて matrix を設定しておいた

**Comment by sor4chi** [comment]
https://gist.github.com/belgattitude/838b2eba30c324f1f0033a797bab2e31?permalink_comment_id=4489311
標準のキャッシュ機能よりこっちの方が早いよって話みたい

**Comment by a01sa01to** [comment]
使い方にもよるし、現時点では「Install deps」部分が 5s しかかかってないしそこまで大差ない気はするけどなぁ...
